-- =====================================================================
--  MG SECURITY HRM — STANDALONE PRODUCTION HOTFIX MIGRATION
--  File: employee_address_join_date_hotfix.sql
--  Target: Supabase PostgreSQL (public.employees & employee_join_date_history)
-- =====================================================================
--  Summary of changes:
--    1. Ensures employee_join_date_history table exists with correct schema.
--    2. Replaces log_employee_join_date_change() trigger function with safe
--       text-to-date casting (nullif(btrim(...), '')::date) to fix error 42804.
--    3. Re-attaches trg_employee_join_date_history trigger to public.employees.
--    4. Safely drops unused legacy columns present_address_en and
--       permanent_address_en (confirmed 0 rows populated).
--    5. Preserves all Bangla columns, existing statuses, and join_dates.
-- =====================================================================

-- Step 1: Ensure audit history table exists with expected columns
create table if not exists public.employee_join_date_history (
  id             bigint generated by default as identity primary key,
  employee_id    bigint not null,
  old_join_date  date,
  new_join_date  date,
  changed_by     uuid,
  changed_at     timestamptz not null default now()
);

-- Enable RLS and policies for audit table
alter table public.employee_join_date_history enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'employee_join_date_history'
      and policyname = 'employee_join_date_history_select'
  ) then
    create policy "employee_join_date_history_select"
      on public.employee_join_date_history
      for select to authenticated using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'employee_join_date_history'
      and policyname = 'employee_join_date_history_insert'
  ) then
    create policy "employee_join_date_history_insert"
      on public.employee_join_date_history
      for insert to authenticated with check (true);
  end if;
end $$;

-- Step 2: Replace trigger function with safe date casting
create or replace function public.log_employee_join_date_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.join_date is distinct from new.join_date then
    insert into public.employee_join_date_history (
      employee_id,
      old_join_date,
      new_join_date,
      changed_by,
      changed_at
    )
    values (
      new.id,
      nullif(btrim(old.join_date), '')::date,
      nullif(btrim(new.join_date), '')::date,
      auth.uid(),
      now()
    );
  end if;

  return new;
exception when others then
  -- Fail-safe: log warning but never abort the employee update transaction
  raise warning 'log_employee_join_date_change notice: %', sqlerrm;
  return new;
end;
$$;

-- Step 3: Recreate trigger on public.employees
drop trigger if exists trg_employee_join_date_history on public.employees;
create trigger trg_employee_join_date_history
  after update of join_date on public.employees
  for each row
  execute function public.log_employee_join_date_change();

-- Step 4: Safely drop unused English address columns (verified 0 rows)
alter table public.employees
  drop column if exists present_address_en,
  drop column if exists permanent_address_en,
  drop column if exists address,
  drop column if exists address_bn;

-- Step 5: Ensure new address columns exist
alter table public.employees
  add column if not exists present_post_office text,
  add column if not exists permanent_post_office text,
  add column if not exists present_address_details text,
  add column if not exists permanent_address_details text,
  add column if not exists present_address_bn text,
  add column if not exists permanent_address_bn text,
  add column if not exists perm_division text,
  add column if not exists perm_district text,
  add column if not exists perm_upazila text,
  add column if not exists perm_union text,
  add column if not exists perm_village text,
  add column if not exists perm_street text;

