-- =====================================================================
--  MG SECURITY HRM — MEETING ATTENDANCE PROJECT SCOPE MIGRATION
--  File: project_meeting_attendance_scope_migration.sql
--  Target: Supabase PostgreSQL (public.projects & project_meeting_scope_history)
-- =====================================================================
--  Summary of changes:
--    1. Adds meeting_attendance_enabled (boolean not null default true) to public.projects.
--    2. Backfills any existing NULL values in public.projects to true.
--    3. Creates public.project_meeting_scope_history audit table.
--    4. Attaches log_project_meeting_scope_change() trigger to public.projects.
--    5. Enables Row Level Security (RLS) on the audit table.
-- =====================================================================

-- Step 1: Add meeting_attendance_enabled column to public.projects
alter table public.projects
  add column if not exists meeting_attendance_enabled boolean not null default true;

-- Step 2: Ensure any legacy projects default to true
update public.projects
  set meeting_attendance_enabled = true
  where meeting_attendance_enabled is null;

-- Step 3: Create audit history table for meeting scope changes
create table if not exists public.project_meeting_scope_history (
  id             bigint generated by default as identity primary key,
  project_id     bigint not null,
  previous_state boolean,
  new_state      boolean not null,
  changed_by     uuid,
  changed_at     timestamptz not null default now()
);

-- Step 4: Enable RLS and policies on the audit history table
alter table public.project_meeting_scope_history enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'project_meeting_scope_history'
      and policyname = 'project_meeting_scope_history_select'
  ) then
    create policy "project_meeting_scope_history_select"
      on public.project_meeting_scope_history
      for select to authenticated using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'project_meeting_scope_history'
      and policyname = 'project_meeting_scope_history_insert'
  ) then
    create policy "project_meeting_scope_history_insert"
      on public.project_meeting_scope_history
      for insert to authenticated with check (true);
  end if;
end $$;

-- Step 5: Create trigger function with exception safety
create or replace function public.log_project_meeting_scope_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.meeting_attendance_enabled is distinct from new.meeting_attendance_enabled then
    insert into public.project_meeting_scope_history (
      project_id,
      previous_state,
      new_state,
      changed_by,
      changed_at
    )
    values (
      new.id,
      old.meeting_attendance_enabled,
      new.meeting_attendance_enabled,
      auth.uid(),
      now()
    );
  end if;

  return new;
exception when others then
  -- Fail-safe: log warning but never abort the project transaction
  raise warning 'log_project_meeting_scope_change notice: %', sqlerrm;
  return new;
end;
$$;

-- Step 6: Attach trigger to public.projects
drop trigger if exists trg_project_meeting_scope_history on public.projects;
create trigger trg_project_meeting_scope_history
  after update of meeting_attendance_enabled on public.projects
  for each row
  execute function public.log_project_meeting_scope_change();
