-- =====================================================================
--  MG SECURITY — HRM DATABASE SCHEMA  (Supabase / PostgreSQL)
--  Version: 2.1     Target: Supabase PostgreSQL (Relational Architecture)
-- =====================================================================
--  Instructions:
--    1. Open Supabase Dashboard -> Your Project -> "SQL Editor"
--    2. Click "New Query" -> Paste this entire file -> Click "Run"
--    3. All tables use UTF-8 and enforce RecordID as the core root key.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0) Extensions
-- ---------------------------------------------------------------------
create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------
-- 1) PROJECTS — Project Master Table
-- ---------------------------------------------------------------------
create table if not exists public.projects (
  id                 bigint generated by default as identity primary key,
  project_name       text not null unique,
  project_name_bn    text,
  address            text,
  address_bn         text,
  main_gate_phone    text,
  admin_name         text,
  admin_phone        text,
  admin_whatsapp     text,
  division           text,
  district           text,
  thana              text,
  division_id        text,
  district_id        text,
  upazila_id         text,
  union_id           text,
  village            text,
  street             text,
  start_date         text,
  status             text default 'Active',
  is_active          boolean not null default true,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

-- Additive column migrations for projects
alter table public.projects add column if not exists address text;
alter table public.projects add column if not exists address_bn text;
alter table public.projects add column if not exists admin_name text;
alter table public.projects add column if not exists division text;
alter table public.projects add column if not exists district text;
alter table public.projects add column if not exists thana text;
alter table public.projects add column if not exists division_id text;
alter table public.projects add column if not exists district_id text;
alter table public.projects add column if not exists upazila_id text;
alter table public.projects add column if not exists union_id text;
alter table public.projects add column if not exists village text;
alter table public.projects add column if not exists street text;
alter table public.projects add column if not exists start_date text;
alter table public.projects add column if not exists status text default 'Active';

-- ---------------------------------------------------------------------
-- 2) EMPLOYEES — Master Employee Table (Primary Key: id)
-- ---------------------------------------------------------------------
create table if not exists public.employees (
  id             bigint generated by default as identity primary key,
  employee_id    text,                     -- Badge / Company Employee ID (e.g., 61115)
  full_name      text not null,
  full_name_bn   text,
  father_name    text,
  mother_name    text,
  dob            text,                     -- Date of Birth (DD/MM/YYYY or YYYY-MM-DD)
  phone          text,
  nid            text,
  education      text,
  religion       text,
  height         text,
  weight         text,
  marital_status text,
  spouse_name    text,
  spouse_phone   text,
  ec_name        text,                     -- Emergency Contact Name
  ec_relation    text,                     -- Emergency Contact Relation
  ec_phone       text,                     -- Emergency Contact Phone
  -- Address
  division       text,
  district       text,
  thana          text,
  address        text,
  address_bn     text,
  division_id    text,
  district_id    text,
  upazila_id     text,
  union_id       text,
  village        text,
  street         text,
  -- Job Info
  designation    text,
  project_name   text,
  join_date      text,
  duty_hour      text,
  salary         numeric,
  status         text not null default 'Active',   -- Active | Inactive
  exit_date      text,
  exit_reason    text,
  remarks        text,
  photo_url      text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- Drop obsolete record_id / system_id columns and indexes if existing
alter table if exists public.employees drop column if exists record_id cascade;
alter table if exists public.employees drop column if exists system_id cascade;
drop index if exists public.employees_record_id_idx;

-- Additive column migrations for employees
alter table public.employees add column if not exists division_id text;
alter table public.employees add column if not exists district_id text;
alter table public.employees add column if not exists upazila_id text;
alter table public.employees add column if not exists union_id text;
alter table public.employees add column if not exists village text;
alter table public.employees add column if not exists street text;
alter table public.employees add column if not exists father_name text;
alter table public.employees add column if not exists mother_name text;
alter table public.employees add column if not exists nid text;
alter table public.employees add column if not exists marital_status text;
alter table public.employees add column if not exists spouse_name text;
alter table public.employees add column if not exists spouse_phone text;
alter table public.employees add column if not exists ec_name text;
alter table public.employees add column if not exists ec_relation text;
alter table public.employees add column if not exists ec_phone text;
alter table public.employees add column if not exists address text;
alter table public.employees add column if not exists address_bn text;
alter table public.employees add column if not exists exit_reason text;
alter table public.employees add column if not exists remarks text;

create index if not exists employees_project_idx   on public.employees (project_name);
create index if not exists employees_status_idx    on public.employees (status);
create index if not exists employees_desig_idx     on public.employees (designation);
create index if not exists employees_empid_idx     on public.employees (employee_id);

-- ---------------------------------------------------------------------
-- 3) MANPOWER DEMAND — Project-wise Sanctioned Strength (Parade State)
-- ---------------------------------------------------------------------
create table if not exists public.demand (
  id                 bigint generated by default as identity primary key,
  project_name       text not null unique,
  demand_incharge    integer not null default 0,
  demand_supervisor  integer not null default 0,
  demand_assst_sup   integer not null default 0,
  demand_guard       integer not null default 0,
  demand_lady_guard  integer not null default 0,
  demand_total       integer not null default 0,
  updated_at         timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 4) DISCIPLINARY — Disciplinary Actions (FK: record_id)
-- ---------------------------------------------------------------------
create table if not exists public.disciplinary (
  id              bigint generated by default as identity primary key,
  action_id       text unique,
  ref_no          text,
  ref_no_bn       text,
  employee_sys_id bigint references public.employees(id) on delete cascade,
  employee_id     text,
  employee_id_bn  text,
  full_name       text,
  full_name_bn    text,
  designation     text,
  designation_bn  text,
  project_name    text,
  project_name_bn text,
  action_type     text,
  issue_date      text,
  issue_date_bn   text,
  incident_date   text,
  description     text,
  description_bn  text,
  created_at      timestamptz not null default now()
);

alter table public.disciplinary add column if not exists employee_sys_id bigint references public.employees(id) on delete cascade;

alter table public.disciplinary add column if not exists employee_id_bn text;
alter table public.disciplinary add column if not exists issue_date_bn text;
alter table public.disciplinary add column if not exists description_bn text;

create index if not exists disciplinary_record_idx on public.disciplinary (employee_sys_id);
create index if not exists disciplinary_emp_idx    on public.disciplinary (employee_id);

-- ---------------------------------------------------------------------
-- 5) EXITS — Resignations & Terminations (FK: record_id)
-- ---------------------------------------------------------------------
create table if not exists public.exits (
  id              bigint generated by default as identity primary key,
  exit_id         text unique,
  employee_sys_id bigint references public.employees(id) on delete cascade,
  employee_id     text,
  full_name       text,
  designation     text,
  current_project text,
  join_date       text,
  exit_reason     text,
  exit_date       text,
  issue_date      text,
  created_at      timestamptz not null default now()
);

alter table public.exits add column if not exists employee_sys_id bigint references public.employees(id) on delete cascade;

alter table public.exits add column if not exists employee_id text;

create index if not exists exits_record_idx on public.exits (employee_sys_id);
create index if not exists exits_date_idx   on public.exits (exit_date);

-- ---------------------------------------------------------------------
-- 6) TRANSFERS — Employee Project Transfers (FK: record_id)
-- ---------------------------------------------------------------------
create table if not exists public.transfers (
  id                  bigint generated by default as identity primary key,
  transfer_id         text unique,
  employee_sys_id bigint references public.employees(id) on delete cascade,
  employee_id         text,
  employee_id_bn      text,
  full_name           text,
  full_name_bn        text,
  designation         text,
  designation_bn      text,
  current_project     text,
  current_project_bn  text,
  new_project         text,
  new_project_bn      text,
  transfer_date       text,
  transfer_date_bn    text,
  issues_date         text,
  issues_date_bn      text,
  is_proceed          text default 'No',
  created_at          timestamptz not null default now()
);

alter table public.transfers add column if not exists employee_sys_id bigint references public.employees(id) on delete cascade;

alter table public.transfers add column if not exists employee_id_bn text;
alter table public.transfers add column if not exists transfer_date_bn text;
alter table public.transfers add column if not exists issues_date_bn text;
alter table public.transfers add column if not exists status text;
alter table public.transfers add column if not exists notes text;

create index if not exists transfers_record_idx on public.transfers (employee_sys_id);
create index if not exists transfers_date_idx   on public.transfers (transfer_date);

-- ---------------------------------------------------------------------
-- 7) CAREER / PROMOTION — Promotion & Salary Increments (FK: record_id)
-- ---------------------------------------------------------------------
create table if not exists public.career (
  id                   bigint generated by default as identity primary key,
  change_id            text unique,
  employee_sys_id bigint references public.employees(id) on delete cascade,
  employee_id          text,
  full_name            text,
  project_name         text,
  change_type          text,        -- Promotion | Increment | Both
  effective_date       text,
  current_designation  text,
  new_designation      text,
  previous_salary      numeric,
  increment_amount     numeric,
  new_salary           numeric,
  created_at           timestamptz not null default now()
);

alter table public.career add column if not exists employee_sys_id bigint references public.employees(id) on delete cascade;

alter table public.career add column if not exists notes text;

create index if not exists career_record_idx on public.career (employee_sys_id);
create index if not exists career_date_idx   on public.career (effective_date);

-- ---------------------------------------------------------------------
-- 8) UNIFORM — Uniform Order & Issue Tracking (FK: record_id)
-- ---------------------------------------------------------------------
create table if not exists public.uniform (
  id             bigint generated by default as identity primary key,
  issue_id       text unique,
  employee_sys_id bigint references public.employees(id) on delete cascade,
  employee_id    text,
  full_name      text,
  designation    text,
  project_name   text,
  item_name      text,          -- Shirt | Pant | Cap | Belt | Shoes | Sweater | ID Card
  size_text      text,
  quantity       integer default 1,
  issue_date     text,
  return_date    text,
  condition_text text,          -- New | Good | Damaged
  status         text default 'Issued',   -- Issued | Returned | Damaged
  remarks        text,
  created_at     timestamptz not null default now()
);

alter table public.uniform add column if not exists employee_sys_id bigint references public.employees(id) on delete cascade;


create index if not exists uniform_record_idx on public.uniform (employee_sys_id);
create index if not exists uniform_emp_idx    on public.uniform (employee_id);

-- ---------------------------------------------------------------------
-- 9) LEAVES — Leave Applications & Balances (FK: record_id)
-- ---------------------------------------------------------------------
create table if not exists public.leaves (
  id           bigint generated by default as identity primary key,
  leave_id     text unique,
  employee_sys_id bigint references public.employees(id) on delete cascade,
  employee_id  text,
  full_name    text,
  designation  text,
  project_name text,
  leave_type   text,     -- Casual | Sick | Annual | Maternity | Unpaid | Emergency
  from_date    text,
  to_date      text,
  days_count   integer,
  reason       text,
  status       text default 'Pending',   -- Pending | Approved | Rejected | Cancelled
  applied_on   text,
  approved_by  text,
  created_at   timestamptz not null default now()
);

alter table public.leaves add column if not exists employee_sys_id bigint references public.employees(id) on delete cascade;


create index if not exists leaves_record_idx on public.leaves (employee_sys_id);
create index if not exists leaves_status_idx on public.leaves (status);

-- ---------------------------------------------------------------------
-- 10) MEETINGS & ATTENDANCE (FK: record_id)
-- ---------------------------------------------------------------------
create table if not exists public.meetings (
  id            bigint generated by default as identity primary key,
  meeting_id    text unique,
  meeting_date  text,
  title         text,
  venue         text,
  agenda        text,
  created_by    text,
  created_at    timestamptz not null default now()
);

create table if not exists public.meeting_attendance (
  id           bigint generated by default as identity primary key,
  meeting_id   text not null,
  employee_sys_id bigint references public.employees(id) on delete cascade,
  employee_id  text,
  full_name    text,
  designation  text,
  project_name text,
  status       text default 'Present',   -- Present | Absent | Late | Excused
  remarks      text
);

alter table public.meeting_attendance add column if not exists employee_sys_id bigint references public.employees(id) on delete cascade;


create index if not exists att_meeting_idx on public.meeting_attendance (meeting_id);
create index if not exists att_record_idx  on public.meeting_attendance (employee_sys_id);

-- ---------------------------------------------------------------------
-- 11) REFERENCE TABLES — Divisions / Districts / Thanas / Designations
-- ---------------------------------------------------------------------
create table if not exists public.divisions (
  division_id   integer primary key,
  division_name text not null
);

create table if not exists public.districts (
  district_id   integer primary key,
  division_id   integer,
  district_name text not null
);

create table if not exists public.thanas (
  thana_id    integer primary key,
  district_id integer,
  thana_name  text not null
);

create table if not exists public.designations (
  desig_id        integer primary key,
  designation     text not null,
  designation_bn  text
);

-- ---------------------------------------------------------------------
-- 12) APP SETTINGS — Company Profile, Logo, Salary Map, Preferences
-- ---------------------------------------------------------------------
create table if not exists public.app_settings (
  setting_key   text primary key,
  setting_value jsonb,
  updated_at    timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 13) PROFILES — User Authentication & Role-Based Access Control (RBAC)
-- ---------------------------------------------------------------------
create table if not exists public.profiles (
  id            uuid primary key references auth.users(id) on delete cascade,
  email         text,
  full_name     text,
  role          text not null default 'viewer',   -- owner | admin | manager | supervisor | viewer
  project_scope text,                             -- Assigned project when role is manager
  is_active     boolean not null default true,
  last_login    timestamptz,
  created_at    timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', new.email),
    'viewer'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------
-- 14) ACTIVITY LOG — Audit Trail
-- ---------------------------------------------------------------------
create table if not exists public.activity_log (
  id          text primary key default gen_random_uuid()::text,
  user_id     uuid,
  user_email  text,
  action      text,        -- insert | update | delete
  table_name  text,
  record_ref  text,
  detail      text,
  created_at  timestamptz not null default now()
);

create index if not exists activity_created_idx on public.activity_log (created_at desc);

-- ---------------------------------------------------------------------
-- 15) RECRUITMENT ARCHIVE — Candidate History
-- ---------------------------------------------------------------------
create table if not exists public.recruitment_archive (
  archive_id     text primary key default gen_random_uuid()::text,
  candidate_name text,
  designation    text,
  project_name   text,
  result         text,        -- Confirmed | Rejected
  employee_id    text,
  decided_at     timestamptz not null default now(),
  notes          text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index if not exists recruitment_archive_at_idx on public.recruitment_archive (decided_at desc);

-- =====================================================================
--  RELATIONAL INTEGRITY: Clean up obsolete record_id constraints
-- =====================================================================
do $$
begin
  alter table if exists public.transfers drop constraint if exists fk_transfers_record_id;
  alter table if exists public.disciplinary drop constraint if exists fk_disciplinary_record_id;
  alter table if exists public.exits drop constraint if exists fk_exits_record_id;
  alter table if exists public.career drop constraint if exists fk_career_record_id;
  alter table if exists public.leaves drop constraint if exists fk_leaves_record_id;
  alter table if exists public.uniform drop constraint if exists fk_uniform_record_id;
  alter table if exists public.meeting_attendance drop constraint if exists fk_meeting_attendance_record_id;
exception
  when others then
    raise notice 'Constraint cleanup notice: %', sqlerrm;
end $$;

-- =====================================================================
--  ROW LEVEL SECURITY (RLS)
-- =====================================================================
alter table public.employees            enable row level security;
alter table public.projects             enable row level security;
alter table public.demand               enable row level security;
alter table public.disciplinary         enable row level security;
alter table public.exits                enable row level security;
alter table public.transfers            enable row level security;
alter table public.career               enable row level security;
alter table public.uniform              enable row level security;
alter table public.leaves               enable row level security;
alter table public.meetings             enable row level security;
alter table public.meeting_attendance   enable row level security;
alter table public.divisions            enable row level security;
alter table public.districts            enable row level security;
alter table public.thanas               enable row level security;
alter table public.designations         enable row level security;
alter table public.app_settings         enable row level security;
alter table public.profiles             enable row level security;
alter table public.activity_log         enable row level security;
alter table public.recruitment_archive  enable row level security;

create or replace function public.my_role()
returns text
language sql
stable
security definer set search_path = public
as $$
  select coalesce((select role from public.profiles where id = auth.uid()), 'viewer');
$$;

-- Authenticated data access policies
do $$
declare
  t text;
  data_tables text[] := array[
    'employees','projects','demand','disciplinary','exits','transfers',
    'career','uniform','leaves','meetings','meeting_attendance',
    'divisions','districts','thanas','designations','app_settings',
    'recruitment_archive'
  ];
begin
  foreach t in array data_tables loop
    execute format('drop policy if exists "%s_select" on public.%I', t, t);
    execute format('drop policy if exists "%s_insert" on public.%I', t, t);
    execute format('drop policy if exists "%s_update" on public.%I', t, t);
    execute format('drop policy if exists "%s_delete" on public.%I', t, t);

    execute format(
      'create policy "%s_select" on public.%I for select to authenticated using (true)', t, t);
    execute format(
      'create policy "%s_insert" on public.%I for insert to authenticated with check (true)', t, t);
    execute format(
      'create policy "%s_update" on public.%I for update to authenticated using (true) with check (true)', t, t);
    -- Delete restricted to Owner and Admin roles
    execute format(
      'create policy "%s_delete" on public.%I for delete to authenticated using (public.my_role() in (''owner'',''admin''))', t, t);
  end loop;
end $$;

-- Profiles Policies
drop policy if exists "profiles_select" on public.profiles;
drop policy if exists "profiles_update_self" on public.profiles;
drop policy if exists "profiles_admin_all" on public.profiles;

create policy "profiles_select" on public.profiles
  for select to authenticated using (true);

create policy "profiles_update_self" on public.profiles
  for update to authenticated
  using (id = auth.uid())
  with check (id = auth.uid() and role = (select role from public.profiles p where p.id = auth.uid()));

create policy "profiles_admin_all" on public.profiles
  for all to authenticated
  using (public.my_role() in ('owner','admin'))
  with check (public.my_role() in ('owner','admin'));

-- Activity Log Policies
drop policy if exists "activity_select" on public.activity_log;
drop policy if exists "activity_insert" on public.activity_log;

create policy "activity_select" on public.activity_log
  for select to authenticated using (true);

create policy "activity_insert" on public.activity_log
  for insert to authenticated with check (true);




ALTER TABLE public.disciplinary DROP COLUMN IF EXISTS record_id;
ALTER TABLE public.disciplinary DROP COLUMN IF EXISTS system_id;
ALTER TABLE public.exits DROP COLUMN IF EXISTS record_id;
ALTER TABLE public.exits DROP COLUMN IF EXISTS system_id;
ALTER TABLE public.transfers DROP COLUMN IF EXISTS record_id;
ALTER TABLE public.transfers DROP COLUMN IF EXISTS system_id;
ALTER TABLE public.career DROP COLUMN IF EXISTS record_id;
ALTER TABLE public.career DROP COLUMN IF EXISTS system_id;
ALTER TABLE public.uniform DROP COLUMN IF EXISTS record_id;
ALTER TABLE public.uniform DROP COLUMN IF EXISTS system_id;
ALTER TABLE public.leaves DROP COLUMN IF EXISTS record_id;
ALTER TABLE public.leaves DROP COLUMN IF EXISTS system_id;
ALTER TABLE public.meeting_attendance DROP COLUMN IF EXISTS record_id;
ALTER TABLE public.meeting_attendance DROP COLUMN IF EXISTS system_id;

-- ---------------------------------------------------------------------
-- Real-Time WebSockets Replication
-- ---------------------------------------------------------------------
-- Enable PostgreSQL Real-Time publications for live updates in Supabase:
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    alter publication supabase_realtime add table public.projects;
    alter publication supabase_realtime add table public.employees;
  end if;
exception when others then
  null;
end $$;

